In [1]:
import numpy as np

# Array operations

In [2]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [3]:
print(a1)
a2

[1 2 3 4 5]


array([ 6,  7,  8,  9, 10])

In [4]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [5]:
a1-a2

array([-5, -5, -5, -5, -5])

In [6]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [7]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
a1//a2

array([0, 0, 0, 0, 0])

In [9]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

# Broadcasting 

In [10]:
l=[10,20,30,40]
arr=np.array(l)

In [11]:
arr+10

array([20, 30, 40, 50])

# deep and shallow copy

In [12]:
a= np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [15]:
slice=a[:5]
slice=slice *10

In [16]:
slice

array([10, 20, 30, 40, 50])

In [17]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# Matrix operation

In [18]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [19]:
A

array([[1, 2],
       [3, 4]])

In [20]:
B

array([[5, 6],
       [7, 8]])

In [21]:
A*B

array([[ 5, 12],
       [21, 32]])

In [22]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [24]:
A*B # that is not the correct way to multiply matrix

array([[ 5, 12],
       [21, 32]])

In [25]:
A@B

array([[19, 22],
       [43, 50]])

In [26]:
#transpos means rows becomes columns

In [27]:
A.T

array([[1, 3],
       [2, 4]])

# Advance Array Manipulation

### stacking Array

In [29]:
A

array([[1, 2],
       [3, 4]])

In [30]:
B

array([[5, 6],
       [7, 8]])

In [32]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

In [33]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

`slplitting array`

In [36]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.vsplit(c,2)