In [1]:
import numpy as np


# basic array creation

In [2]:
arr= np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [7]:
a=[1,2,3,4,5.93] # one dimensional or vector

In [8]:
a

[1, 2, 3, 4, 5.93]

In [9]:
np.array(a)

array([1.  , 2.  , 3.  , 4.  , 5.93])

In [11]:
l=[[1,2,3,4],[3,4,5,6],[3,5,5,5]]
l

[[1, 2, 3, 4], [3, 4, 5, 6], [3, 5, 5, 5]]

In [13]:
np.array(l) # 2d matrix

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [3, 5, 5, 5]])

# Array generation function

In [15]:
arr=np.arange(1,30)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [16]:
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [18]:
arr=np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
arr=np.ones((5,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [24]:
arr=np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

# Random generation function

In [26]:
np.random.rand(10) # random number between 0 to 1 normalization

array([0.236262  , 0.30667002, 0.790271  , 0.12605328, 0.54794903,
       0.52557968, 0.47948734, 0.45598023, 0.45551463, 0.03286403])

In [27]:
np.random.randn(10) # between -3 to 3

array([ 1.28305874,  0.46614338,  0.09083806, -1.11957417,  0.82248783,
        0.15467506,  2.64978874,  1.48816276,  0.86294886,  0.39898102])

In [28]:
np.random.randint(6)

2

In [29]:
np.random.randint(10,20,10)

array([16, 17, 15, 14, 14, 16, 17, 15, 11, 13], dtype=int32)

# Array attributies

In [30]:
arr=np.array([[1,2,3,4],[3,4,5,6],[3,5,5,5]])
arr

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [3, 5, 5, 5]])

In [31]:
arr.shape

(3, 4)

In [32]:
arr.size

12

In [34]:
arr.dtype

dtype('int64')

# Array method

In [36]:
arr.min()

np.int64(1)

In [37]:
arr.max()

np.int64(6)

In [38]:
arr.sum()

np.int64(46)

In [39]:
np.sum(arr,axis=0)

array([ 7, 11, 13, 15])

In [40]:
np.sum(arr,axis=1)

array([10, 18, 18])

In [41]:
arr.mean()

np.float64(3.8333333333333335)

In [42]:
arr.std()

np.float64(1.404358295529393)

In [43]:
arr.argmax()

np.int64(7)

In [44]:
arr.argmin()

np.int64(0)

# Reshaping and resizing

In [48]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [51]:
arr= arr.reshape(6,5)