In [1]:
import numpy as np

# NUMPY INDEXIXING AND SLICING OF VECTORS

In [4]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
arr[9]

np.int64(20)

In [7]:
arr[1:5]

array([12, 13, 14, 15])

In [8]:
arr[:4]

array([11, 12, 13, 14])

In [9]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [13]:
arr_slice=arr[3::2]

In [14]:
arr[4]

np.int64(15)

# NUMPY INDEXING AND SLICING OF MATRIX

In [15]:
arr=np.arange(1,31).reshape(6,5)

In [16]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [19]:
arr[1] # target rows

array([ 6,  7,  8,  9, 10])

In [23]:
arr[0,4] # always rows target first and then columns

np.int64(5)

In [24]:
arr[5,4]

np.int64(30)

In [26]:
slice=arr[0:2,1:3]

In [27]:
slice

array([[2, 3],
       [7, 8]])

In [28]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [29]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

# BOOLEAN INDEXING

In [33]:
arr=np.arange(11,21)

In [34]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [35]:
bool_index=arr%2==0

In [36]:
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [37]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])